### ISSUE TITLE
Tree Rendering

### ISSUE THREAD

**Issue by davecaruso** [davecaruso/elemental4#29]
A tree is defined as
```
interface Tree {
  /** The element itself. */
  elem: Elem;
  /** Parent 1. null if no parents (a base element) */
  parent1: Tree | null;
  /** Parent 2. null if no parents OR the parent1 is combined with itself */
  parent2: Tree | null;
}
```
The ui calls these two functions
- `initTreeCanvas(tree: Tree)`
- `endTreeCanvas`

And we have an `update()` loop function.

This is already added, but the tree rendering code is NOT implemented at all

**Comment by Nv7-GitHub** [comment]
I could add the tree calculation code, although I don't know how to do rendering

**Comment by davecaruso** [comment]
tree calc is already finished @Nv7-GitHub

**Comment by davecaruso** [comment]
they has not pushed any code yet but @Zolo101 is working on their own implementation of this.
