### ISSUE TITLE
Voting equations for anarchy

### ISSUE THREAD

**Issue by bolt1117** [davecaruso/elemental4#49]
What are the voting equations for the Anarchy (One Vote) server? 
Im trying to setup my own anarchy Elemental 4 private server, where anything that gets submitted is added immediately.

I tried setting both equations to 1, and that did nothing.

Can anyone help?

**Comment by davecaruso** [comment]
anarchy.elemental4.net has both equations set to 0 but i think only the threshold needs to be 0

**Comment by bolt1117** [comment]
Ok! Thanks for the help!
