### ISSUE TITLE
Prevent IDs from being shown

### ISSUE THREAD

**Issue by icecream17** [davecaruso/elemental4#66]
Somewhat of a security issue:

When I click on "Export Login" it says:
![image](https://user-images.githubusercontent.com/58114641/102720327-50fbe300-42b9-11eb-9ead-338e2cedb2c7.png)

However, you can see IDs in the debug info of an element...
![image](https://user-images.githubusercontent.com/58114641/102720375-87d1f900-42b9-11eb-9fe2-d7b551475ccd.png)

So theoretically you could import the ID and impersonate someone.

**Comment by davecaruso** [comment]
the `creators` list is actually a public id. this isnt exactly documented anywhere but you have a private id and a public id. the private one is required to impersonate someone, but the public one is just linked to the username and cannot be used to suggest with.
