### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Plasmath** [davecaruso/elemental4#73]
Whenever I try to make a new suggestion on the main server, it gives the text 'Server Error: an error occurred during loading.'
![image](https://user-images.githubusercontent.com/77946264/105651674-8336cc80-5e85-11eb-8796-4dc31d1979db.png)
I'm not sure if this is a bug from the code or the server, because suggestions seem to work for all servers that aren't the main one.

**Comment by davecaruso** [comment]
many people in the discord were experiencing this. looking at some code that dialog box appears at

![image](https://user-images.githubusercontent.com/24465214/105664559-f995f780-5ea2-11eb-9a0e-0c283f4f784b.jpeg)

which comes from a error handler of any error inside of the suggestion logic

![image](https://user-images.githubusercontent.com/24465214/105664593-0adf0400-5ea3-11eb-8c79-95aee8d4132d.jpeg)

as you can see the error isnt even logged, so i probably should go and check that out a bit and see if any issues exist.
