### ISSUE TITLE
Just remove the searchbar at this point

### ISSUE THREAD

**Issue by Plasmoxxie** [davecaruso/elemental4#88]
The search bar will not stop forcing me to type in it. it is nearly impossible to make elements because of it. please just remove it.

**Comment by Plasmoxxie** [comment]
Its really not useful anyway.

**Comment by davecaruso** [comment]
duplicate of fixed bug #82. i can not reproduce this bug on the latest build, however i have noticed firefox not being able to search and safari not being able to open the game at all. those can be investigated later i guess.
